"""
Method 2: Build a Custom RLM REPL Harness from ScratchIf you are training or fine-tuning your own model (e.g., using a system prompt to teach it to write code blocks), you must build the orchestrator framework. This code relies on a loop that extracts the model's generated code, runs it using Python’s exec(), captures the outputs, and feeds them back.Here is a minimal, fully functional setup using the standard library:
"""



import sys
import io
import re

class RLMOrchestrator:
    def __init__(self, full_context: str):
        # The core environment where variables persist across iterations
        self.repl_globals = {
            "context": full_context,  # The long context lives here as a variable
            "results": []
        }
        self.system_prompt = (
            "You are a Recursive Language Model (RLM). You cannot see the full text directly.\n"
            "Instead, write Python code blocks within ```python ... ``` to slice, search,\n"
            "or process the 'context' variable. Use print() to inspect your code's output.\n"
            "Once you find the answer, reply with: FINAL: <your final answer>"
        )

    def execute_repl_block(self, code_string: str) -> str:
        """Executes the code block generated by the LLM and captures print outputs."""
        stdout_capture = io.StringIO()
        sys.stdout = stdout_capture
        try:
            # Executes code natively inside the continuous state namespace
            exec(code_string, self.repl_globals)
            output = stdout_capture.getvalue()
        except Exception as e:
            output = f"REPL Error: {str(e)}"
        finally:
            sys.stdout = sys.__stdout__
        return output

    def run_inference_loop(self, user_query: str, llm_client):
        """The core Read-Eval-Print Loop orchestrator."""
        messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user", "content": f"Task: {user_query}. You can start inspecting the context variable."}
        ]
        
        for turn in range(10):  # Cap iterations to avoid infinite loops
            # 1. READ: Call your LLM model
            response = llm_client.generate(messages)
            content = response.text
            print(f"\n--- [Model Turn {turn}] ---\n{content}")

            if "FINAL:" in content:
                return content.split("FINAL:")[-1].strip()

            # 2. EVALUATE: Extract the ```python code block ```
            code_match = re.search(r"```python\s*(.*?)\s*```", content, re.DOTALL)
            if code_match:
                code_to_run = code_match.group(1)
                # Run code inside the REPL and capture stdout
                repl_output = self.execute_repl_block(code_to_run)
            else:
                repl_output = "Error: Please wrap your code in a standard ```python ``` block."

            # 3. PRINT / LOOP: Append REPL execution back into history as system feedback
            print(f"-> [REPL Output]:\n{repl_output}")
            messages.append({"role": "assistant", "content": content})
            messages.append({"role": "user", "content": f"REPL Execution Output:\n{repl_output}"})

        return "Max execution turns reached without final answer."
"""
Key Rules for Production Safety ⚠️If you deploy this architecture into a live production workflow, avoid using raw exec() on your host machine. Because the RLM generates code autonomously, execute the model's REPL steps using sandbox infrastructure, such as:Docker containers via Docker SDK for Python.Dedicated agent micro-sandboxes like the E2B Development Environment.Are you aiming to integrate an active cloud platform like E2B/Docker for production security, or are you looking to implement the recursive "sub-agent" feature where the REPL spawns smaller model calls to look at the data slices?
"""
